// interface FlightData {
// 	hex: string;
// 	type: string;
// 	flight: string;
// 	r: string;
// 	t: string;
// 	alt_baro: number;
// 	alt_geom: number;
// 	gs: number;
// 	ias: number;
// 	tas: number;
// 	mach: number;
// 	wd: number;
// 	ws: number;
// 	oat: number;
// 	tat: number;
// 	track: number;
// 	track_rate: number;
// 	roll: number;
// 	mag_heading: number;
// 	true_heading: number;
// 	baro_rate: number;
// 	geom_rate: number;
// 	squawk: string;
// 	emergency: string;
// 	category: string;
// 	nav_qnh: number;
// 	nav_altitude_mcp: number;
// 	nav_altitude_fms: number;
// 	nav_heading: number;
// 	lat: number;
// 	lon: number;
// 	nic: number;
// 	rc: number;
// 	seen_pos: number;
// 	version: number;
// 	nic_baro: number;
// 	nac_p: number;
// 	nac_v: number;
// 	sil: number;
// 	sil_type: string;
// 	gva: number;
// 	sda: number;
// 	alert: number;
// 	spi: number;
// 	mlat: any[];
// 	tisb: any[];
// 	messages: number;
// 	seen: number;
// 	rssi: number;
// 	dst: number;
// 	dir: number;
// }

interface FlightData {
	icao24: string;
	callsign: string;
	origin_country: string;
	time_position: number;
	last_contact: number;
	longitude: number;
	latitude: number;
	baro_altitude: number;
	on_ground: boolean;
	velocity: number;
	true_track: number;
	vertical_rate: number;
	sensors: number;
	geo_altitude: number;
	squawk: number;
	spi: boolean;
	position_source: number;
	category: number;
}
